sudo: false
language: python
python:
    - "3.6"
script:
- echo $PYCLOUDMESSENGER > ./creds.json
- #python3 -m pytest tests/basic.py --credentials=./creds.json -srx -s
- python3 local_platform/musketeer.py &
- python3 -m pytest tests/basic.py --credentials=local_credential_sample.json --platform=local -srx -s
- rm ./creds.json
